# Generated by Django 4.2.30 on 2026-09-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_uploadeddocument_uploadeddocumentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocumentchunk',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
